### ISSUE TITLE
Cannot read property 'forEach' of undefined]

### ISSUE THREAD

**Issue by Sebojan** [rthewhite/homebridge-homewizard#49] opened 2016-12-30 15:13 UTC
I followed your install guide step by step , and installed everything. It starts working but 
when starting Homebridge, everything runs fine. The app shows the computer as off, but when I try to power on, I see homebridge stop and provide the following:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[12/30/2016, 2:58:26 PM] Loaded plugin: homebridge-homewizard
[12/30/2016, 2:58:26 PM] Registering platform 'homebridge-homewizard.HomeWizard'
[12/30/2016, 2:58:26 PM] ---
[12/30/2016, 2:58:26 PM] Loaded config.json with 0 accessories and 1 platforms.
[12/30/2016, 2:58:26 PM] ---
[12/30/2016, 2:58:26 PM] Loading 1 platforms...
[12/30/2016, 2:58:26 PM] Initializing HomeWizard platform...
[12/30/2016, 2:58:26 PM] Loading 0 accessories...
[12/30/2016, 2:58:26 PM] Running : homebridge-homewizard 0.0.50
[12/30/2016, 2:58:27 PM] Successfully retrieved accessories from HomeWizard
[12/30/2016, 2:58:27 PM] Failed to retrieve accessories from HomeWizard
[12/30/2016, 2:58:27 PM] [TypeError: Cannot read property 'forEach' of undefined]

i have installed 
node --version v4.0.0
and home bridge version 0.4.16

I don't know much from coding so i hope you have enough info 
If not let me know

**Comment by rthewhite** [comment] 2016-12-30 17:20
Duplicate off: https://github.com/rthewhite/homebridge-homewizard/issues/48

**Closed by rthewhite** 2016-12-30 17:20 UTC
