### ISSUE TITLE
Homebridge stops after a while (refresh)

### ISSUE THREAD

**Issue by Justme1974** [rthewhite/homebridge-homewizard#68] opened 2017-10-10 19:21 UTC
I installed a Rasp Pi with homebridge and a Homewizard and Harmony plugin. I configured the Config file and setup my iphone (homekit) and everthing is working fine with siri. But after a while (can be 2 hours or a day) the homebridge stops. He doen’t retrieve any power state anymore and says: refresh all the time. And the plugins will not work anymore.

I’ve tried everything: update avahi, delete the persist and accessories folder, changed the config file (other macadres and pin), update the homebridge, installed the homekit serveral times. It doesn’t mind if i’am on wifi or utp. All the same. 
I’m not an expert, but it’s drives me crazy. 
Any suggestions?

Thanxs

**Comment by ronzelver** [comment] 2017-10-10 19:49
Same here, last week it ran for 5 days in a row and for some reason I have to restart the service now at least on a daily basis.  I've enabled the DEBUG flag for homebridge as well as for the homebridge-homewizard plugin to see if it points me in a certain direction. See also #64.

**Comment by ubram** [comment] 2017-10-16 18:49
I have exactly the same issue. Reconfigurated/updated several times but cannot resolve the issue. I restart the service now every night, but still sometimes it doesn't work.

**Comment by rhelweg** [comment] 2017-10-22 09:47
And the same issue over here as well. After only a few hours, the only thing I see is
[2017-10-22 01:30:14] [HomeWizard] Refresh...
[2017-10-22 01:31:14] [HomeWizard] Refresh...
[2017-10-22 01:32:14] [HomeWizard] Refresh...
[2017-10-22 01:33:14] [HomeWizard] Refresh...
[2017-10-22 01:34:14] [HomeWizard] Refresh...
[2017-10-22 01:35:14] [HomeWizard] Refresh...
[2017-10-22 01:36:14] [HomeWizard] Refresh...
[2017-10-22 01:37:14] [HomeWizard] Refresh...
etc. etc.
Removing accessories and persist folders, changing config file (MAC address, PIN) completely reinstalling everything (Rasp and IOS) and still after a few hours everything stops.
I was using HomeBridge for HomeWizard, Harmony and ICY (E-Thermostaat) but after the last complete reinstall I'm only using HomeWizard. It didn't help...

**Comment by ronzelver** [comment] 2017-10-24 20:17
Strange thing is that some Homewizard-coupled devices are still reporting a status on 1 minute intervals, while all other responses, even from other Homebridge plugins, are no longer processed?!?

`Oct 24 11:28:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:28:16] [HomeWizard] Refresh...
Oct 24 11:28:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:28:16] [HomeWizard] Retrieved currentPosition WindowCovering for: Rolluik is:0
Oct 24 11:28:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:28:16] [HomeWizard] Retrieved positionState WindowCovering for: Rolluik is:2
Oct 24 11:28:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:28:16] [HomeWizard] Retrieved currentPosition WindowCovering for: Zonwering is:100
Oct 24 11:28:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:28:16] [HomeWizard] Retrieved positionState WindowCovering for: Zonwering is:2
Oct 24 11:29:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:29:16] [HomeWizard] Refresh...
Oct 24 11:29:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:29:16] [HomeWizard] Retrieved currentPosition WindowCovering for: Rolluik is:0
Oct 24 11:29:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:29:16] [HomeWizard] Retrieved positionState WindowCovering for: Rolluik is:2
Oct 24 11:29:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:29:16] [HomeWizard] Retrieved currentPosition WindowCovering for: Zonwering is:100
Oct 24 11:29:16 SACLRPi3 homebridge[1027]: [2017-10-24 11:29:16] [HomeWizard] Retrieved positionState WindowCovering for: Zonwering is:2`

As you can see, only the WindowCovering devices (Homebridge -> Homewizard -> devices) are still reporting.

**Comment by Martinvdm** [comment] 2017-10-30 18:04
Same issue here. We using some old version before. e.g 0.43, witch does not had this issue.

**Comment by seekelen** [comment] 2017-11-13 09:33
Same issue here.
How do I install an older version? I tried:

sudo npm install -g homebridge-homewizard -v0.0.50

But 0.0.59 still remains the active version

**Comment by rthewhite** [comment] 2017-11-13 09:35
Uninstall globally using:
npm uninstall -g homebridge-homewizard 

Install a specific version using @ like:
npm install -g homebridge-homewizard@0.0.50

**Comment by rthewhite** [comment] 2017-11-13 09:41
Closing this one as a duplicate of https://github.com/rthewhite/homebridge-homewizard/issues/64

**Closed by rthewhite** 2017-11-13 09:41 UTC
