### ISSUE TITLE
Radiator valve Smartwares SHS-53000

### ISSUE THREAD

**Issue by ygageot** [rthewhite/homebridge-homewizard#12] opened 2016-02-24 10:10 UTC
I have one valve Smartwares SHS-53000 and I try to implement it. 
The logical choice is a **Thermostat**.
I can get the **TargetTemperature** with swlist (tte)
I can set the **TargetTemperature** with for exemple : /sw/2/settarget/21
I can get the **TargetTemperature**.

But I can't get the internal **CurrentTemperature** of the valve  ( it is a global problem with this valve !)

I think in one solution with searching a thermometer in the same HomeKit room. 
But I don't know if the HAP can give me the architecture Home/Zone/Room/Accessoiries.
Have you an idea ?

**Comment by ygageot** [comment] 2016-02-28 10:43
I just proposed an first implementation of this device.
In these version the current temperature is set to the target temperature.
I have some ideas for next version about these current temperature...
A "good" version is to search in the HomeKit database if there is a thermometer in the same room, but for the moment I don't know how to do that easily.
An other direction is to add in the config.json a parameter where you place the correspondances between valves and thermometers.
An other is to take the first thermometer or calculate the mean between thermometers
...
Help me to choose !

**Comment by rthewhite** [comment] 2016-02-28 20:43
I had a quick look at both Homebridge and HAP but couldn't find any interface to retrieve the room for a accessory. Might be that i overlooked it but couldn't find in the source, when looking for it.

I think the second option is then the best, make a correlation between the valve and thermometer in the config file. This can be a simple mapping between valve id and thermometer id.

Currently accessories within this plugin are not aware of other accessories and i think we should keep it that way. So what i purpose is that you pass the id of the thermometer to the valve, and then do the get temperature api call in the valve class. Just like how it's done in the thermometer class it self, you can use the getStatus api call for it, just pass it the thermometer id specified in the config. Have a look in the thermometer class on how to setup the CurrentTemperature characteristic, you need to see the minValue property otherwise negative values won't work.

Shall i merge in your current implementation and release, or do you want to fix the current temperature first?

**Comment by ygageot** [comment] 2016-02-28 21:03
You can wait. For the mapping I was thinking for a mapping between the names, not the ids like for filtering. The ids are more stable in HW, the names in HB !! 
What is your choice ?

**Comment by rthewhite** [comment] 2016-02-28 21:08
Use the names, i used them for the filtering because people that use the plugin usually don't see the id's.
Next to that i don't know what the behavior of HomeWizard is when you remove an accessory and add another one, might re-use the id then, causing strange/unexpected behavior. Next to that the config file is probably more clear if you see some names instead of id's :+1:

**Comment by rthewhite** [comment] 2016-02-29 22:51
Think we can close this one, since it's implemented and release in 0.0.31 :+1:

**Closed by rthewhite** 2016-02-29 22:51 UTC
