### ISSUE TITLE
KAKU ASUN-650 shutters support

### ISSUE THREAD

**Issue by Atm0zfear** [rthewhite/homebridge-homewizard#35] opened 2016-03-16 15:04 UTC
Although update 0.0.44 solves the biggest issue (my shutters are now not seen as lightbulbs anymore) I would like to control them as real shutters.
I don't know how you support the somfy sunscreens, but maybe you can implement more switchtypes such as GaragedoorOpener (see: https://developer.apple.com/library/ios/documentation/HomeKit/Reference/HMService_Class/index.html#//apple_ref/doc/constant_group/Accessory_Service_Types).
I can also tell you that ASUN-650 works like this:
Off: shutters go down.
Off again: shutters stop going down and remain in their current position.
On: shutters go up.
On again: shutters stop going up and remain in their current position.
Let me know how I can be of assistance!

**Comment by sabiwa** [comment] 2016-03-16 16:34
This issue is the same issue as #34

**Comment by rthewhite** [comment] 2016-03-16 17:45
Indeed looks like a duplicate of #34, closing this one continuing in the other issue.

**Closed by rthewhite** 2016-03-16 17:45 UTC
